#!/bin/sh

# 1. Get all staged files, excluding deleted ones
STAGED_FILES=$(git diff --cached --name-only)

# 2. Exit early if no files are staged
if [ -z "$STAGED_FILES" ]; then # -z is this string empty?
    exit 0
fi

codex exec --ephemeral "Code review staged changes" \
      --output-schema ./schema.json \
      2>/dev/null \
      | jq -r -f ./review-format.jq

# 2>/dev/null prevents the output of all progress, reasoning and errors