services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: neondb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kysely:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  pgdata:
