services:
  api:
    image: lydscho72/terminology:test
    ports:
      - "3001:3001"
    build: .
    depends_on:
      - neo4j
    volumes:
      - .:/app

  neo4j:
    image: neo4j:latest
    volumes:
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/config:/config
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    secrets:
      - neo4j_auth_file
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

secrets:
  neo4j_auth_file:
    file: ./secrets/neo4j_auth.txt
volumes:
  pgdata:
