# API
FROM python:3.11
WORKDIR /api
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY ./api /api
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8000"]
