services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  api:
    depends_on:
      neo4j:
        condition: service_healthy
    build: .
    container_name: fastapi-api
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: "no"
    env_file: ".env"
  web-app:
    depends_on:
      api:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react_dev
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app # Hot-reloads changes by syncing your local folder to /app
      - /app/node_modules # Keeps node_modules inside Docker instead of replacing it with /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

#   open-webui:
#     image: ghcr.io/open-webui/open-webui:main
#     ports:
#       - "4000:8080"
#     environment:
#       - OLLAMA_BASE_URL=http://host.docker.internal:12434
#       - WEBUI_AUTH=false
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     volumes:
#       - open-webui:/app/backend/data
# volumes:
#   open-webui:
