services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  api:
    depends_on:
      neo4j:
        condition: service_healthy
    build: .
    container_name: fastapi-api
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: "no"
    env_file: ".env"
  web-app:
    depends_on:
      api:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react_dev
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app # Hot-reloads changes by syncing your local folder to /app
      - /app/node_modules # Keeps node_modules inside Docker instead of replacing it with /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-cpp
    ports:
      - "9000:9000"
    volumes:
      # Keeps the downloaded model after the container stops.
      - ./hf-cache:/root/.cache/huggingface
    environment:
      LLAMA_ARG_HF_REPO: "ggml-org/gpt-oss-20b-GGUF"
      LLAMA_ARG_HF_FILE: "gpt-oss-20b-mxfp4.gguf" # GGUF File
      LLAMA_ARG_CTX_SIZE: "32768" # Max Context window
      LLAMA_ARG_JINJA: "true" # changes api payload to model-readaable format
      LLAMA_ARG_HOST: "0.0.0.0"
      LLAMA_ARG_PORT: "9000"
    restart: unless-stopped
