import { DB } from "../types/types";
import { Kysely, PostgresDialect } from "kysely";
import { Pool } from "pg";
import "dotenv/config";

// Setup Kysely instance with types generated by Kysely
const db = new Kysely<DB>({
  dialect: new PostgresDialect({
    pool: new Pool({
      connectionString: process.env.DATABASE_URL,
    }),
  }),
});

export default db;
